data: data/cmu_movie
save_model: models/base_model
save_checkpoint_steps: 1000
keep_checkpoint: 20
seed: 3435
train_steps: 20000
valid_steps: 1000
warmup_steps: 10000
report_every: 100

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 3
transformer_ff: 2048
heads: 8

accum_count: 16
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 2048
batch_type: tokens
normalization: tokens
dropout: 0.3
label_smoothing: 0.1
valid_batch_size: 8

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 1
gpu_ranks:
- 0

